### ISSUE TITLE
FBI does not show me the install button.

### ISSUE THREAD

**Issue by bossy00912** [RocketRobz/TWiLightMenu-Launcher#20]
what do i do?

**Comment by RocketRobz** [comment]
How are you booting FBI?

**Comment by bossy00912** [comment]
With cia, lumaCFW

**Comment by RocketRobz** [comment]
Can you install other CIAs?

**Comment by GGB2007** [comment]
ive also got that problem too
no twilightmenu ++

**Comment by GGB2007** [comment]
on home menu

**Comment by takeshineale128** [comment]
> on home menu

install the launcher

**Comment by RocketRobz** [comment]
^ which comes from this repo, in the releases tab.

**Comment by bossy00912** [comment]
I can install some cias, I tried over network and it worked! And all my games and apps disappeared. When I try open eshop I get an error: 007-2075. What do I do?

**Comment by RocketRobz** [comment]
Your SD card might be dying. Try checking it for errors.

**Comment by RocketRobz** [comment]
Go to `This PC`, right-click on your SD card, click `Properties`, click `Tools`, and click `Check`.

**Comment by bossy00912** [comment]
Now it works!

**Comment by RocketRobz** [comment]
You're welcome. :P

**Comment by bossy00912** [comment]
well, i mean the sd card is working, i have only installed twilight menu nad game booter, not the launcher and when i try to do it. i get an error.

**Comment by bossy00912** [comment]
the 3dsx just crashes
